Repository Dankei/Setec-o-Y, pull requests merged in 2024-09, with the labels that each got.

#8 Feito parte do Reply
  backend/model/entity/replyEntity.js
  backend/model/repository/replyRepository.js
  backend/model/service/replyService.js
  backend/router/controller/replyController.js
  backend/router/routes.js
  package-lock.json
Labels: enhancement

#9 Criação da tela inicial e da implementação do tailwind e postcss
  backend/database/database.js
  frontend/public/images/Logo.svg
  frontend/public/images/bg.png
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/LoginScreen.js
  frontend/src/components/SignUpScreen.js
  frontend/src/components/StartScreen.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/IndexPage.js
  package.json
  postcss.config.cjs
  tailwind.config.js
  webpack.config.cjs
Labels: enhancement

#24 Completei a questão de responsividade da tela inicial
  backend/model/service/userService.js
  frontend/src/App.js
  frontend/src/index.css
  frontend/src/pages/LoginScreen.js
  frontend/src/pages/SignUpScreen.js
  frontend/src/pages/StartScreen.js
  frontend/src/routes/ErrorPage.js
  frontend/src/routes/IndexPage.js
  package.json
Labels: enhancement

#27 Daniel refatorando
  backend/backend.js
  backend/database/database.js
  backend/log/logger.js
  backend/model/service/utils/emailUtils.js
  backend/router/controller/userController.js
  package.json
  webpack.config.cjs
Labels: documentation

#31 Tela de Login / Logout funcional com armazenamento de sessão
  backend/backend.js
  backend/router/controller/userController.js
  frontend/src/components/ButtonModern.js
  frontend/src/index.js
  frontend/src/pages/LoginScreen.js
  frontend/src/routes/PrivateRoute.js
  frontend/src/routes/Timeline/HomePage.js
  frontend/src/routes/Timeline/SettingsPage.js
  frontend/src/routes/Timeline/Timeline.js
Labels: enhancement

#35 Corereção issues
  backend/backend.js
  backend/model/repository/tokenRepository.js
  backend/model/repository/userRepository.js
  backend/model/service/userService.js
  backend/router/controller/userController.js
Labels: bug

#38 Tela de login / cadastro oficialmente pronta
  frontend/src/components/NewYeetPop.js
  frontend/src/components/VerificationPopup.js
  frontend/src/pages/LoginScreen.js
  frontend/src/pages/SignUpScreen.js
  frontend/src/routes/Timeline/HomePage.js
  frontend/src/routes/Timeline/ProfilePage.js
  frontend/src/routes/Timeline/SettingsPage.js
Labels: enhancement

#41 comecei a arrumar o follow
  backend/model/service/userService.js
  backend/router/controller/userController.js
  frontend/src/routes/Timeline/Profile.js
  frontend/src/routes/Timeline/ProfilePage.js
Labels: good first issue
